{ pkgs, lib, ... }:

{
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      dns_enabled = true;
    };
  };

  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  virtualisation.podman = {
    enableNvidia = true;
  };

  virtualisation.oci-containers.containers."open-webui-openwebui" = {
    image = "ghcr.io/open-webui/open-webui:cuda";
    volumes = [
      "open-webui_open-webui:/app/backend/data:rw"
    ];
    ports = [
      "3000:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=openwebui"
      "--network=open-webui_default"
    ];
  };
  systemd.services."podman-open-webui-openwebui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-open-webui_default.service"
      "podman-volume-open-webui_open-webui.service"
    ];
    requires = [
      "podman-network-open-webui_default.service"
      "podman-volume-open-webui_open-webui.service"
    ];
    partOf = [
      "podman-compose-open-webui-root.target"
    ];
    wantedBy = [
      "podman-compose-open-webui-root.target"
    ];
  };

  systemd.services."podman-network-open-webui_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f open-webui_default";
    };
    script = ''
      podman network inspect open-webui_default || podman network create open-webui_default
    '';
    partOf = [ "podman-compose-open-webui-root.target" ];
    wantedBy = [ "podman-compose-open-webui-root.target" ];
  };

  systemd.services."podman-volume-open-webui_open-webui" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect open-webui_open-webui || podman volume create open-webui_open-webui
    '';
    partOf = [ "podman-compose-open-webui-root.target" ];
    wantedBy = [ "podman-compose-open-webui-root.target" ];
  };

  systemd.targets."podman-compose-open-webui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
